name: recipes
description: A new Flutter project to display recipes

publish_to: 'none' # Replace with your publish URL if you're publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Adjust based on your SDK version

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2 # Updated provider package version
  http: ^1.2.2 # Updated http package version to ^1.2.2
  # Add any other dependencies you need below

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add dev dependencies like linting tools or testing libraries here

flutter:
  uses-material-design: true

  assets:
  # If you have images you want to use in your app

# Include the following lines for Flutter web compatibility (if applicable)
flutter_web:
  sdk: flutter
